Flagging UI Components
ProgKorn/41127-Software-Design-Studio pull request #57
Opened 2023-10-26 03:34 UTC by gbashour

- Socket IO connection working, Client and Server can communication
- Client connection is established when a Student joins the Exam Session
- Basic events are emitted

2023-10-26 22:56 UTC, abrarbarbhuyia requested changes
GOOD

2023-10-26 22:56 UTC, abrarbarbhuyia commented on client/src/components/FlagNotification.js
> +    const socket = io('http://localhost:4001'); // Change the URL to match your Socket.io server's URL
This might need to be changed to the process.env.REACT_APP_SERVER_URL url

2023-10-26 22:56 UTC, abrarbarbhuyia commented on client/src/components/FlagNotification.js
> +    const socket = io('http://localhost:4001'); // Change the URL to match your Socket.io server's URL
So REACT_APP_SERVER_URL + `:4001`

2023-10-26 22:56 UTC, abrarbarbhuyia commented on server/routes/flag.js
> +        origin: ['http://localhost:3000'] // client URL
Might need to change to ['http://localhost:3000', 'https://sentinel-frontend.vercel.app']

2023-10-26 23:12 UTC, abrarbarbhuyia commented on client/src/components/FlagNotification.js
> +    const socket = io('http://localhost:4001'); // Change the URL to match your Socket.io server's URL
4001 in single quotes tho

2023-10-28 13:23 UTC, abrarbarbhuyia approved these changes
lgt,m

2023-10-28 13:23 UTC, gbashour commented
Updates:
- Admin Notification functionality has been implemented and tested in Exam Session
- Socket IO emits occur in a connected user's individual room associated with their ID
- Styling for Notifications
- Integration for Admin and Student interaction

2023-10-28 13:24 UTC, merged