Fixes for Flagging UI Component Dependencies
ProgKorn/41127-Software-Design-Studio pull request #67
Opened 2023-10-28 13:45 UTC by gbashour

- Removed imports not being used in index.js
- Added socket.io and socket.io-client imports in server and client package.json

2023-10-28 13:57 UTC, gbashour commented
Tested Locally👍

2023-10-28 22:39 UTC, abrarbarbhuyia requested changes
LGTM, just some URLs need fixing

2023-10-28 22:39 UTC, abrarbarbhuyia commented on client/src/components/AdminFlagNotification.js
> +  const url = 'http://localhost:4000' + '/flag';
This needs to be process.env.REACT_APP_SERVER_URL then + '/flag'

2023-10-28 22:39 UTC, abrarbarbhuyia commented on client/src/components/AdminFlagNotification.js
> +    const socket = io('http://localhost' + ':4001'); // Change the URL to match the Socket.IO server URL
Same as this one env var + ':4001'

2023-10-28 22:39 UTC, abrarbarbhuyia commented on client/src/components/FlagNotification.js
> +    const socket = io('http://localhost' + ':4001'); // Change the URL to match the Socket.IO server URL
Same here

2023-10-28 22:39 UTC, abrarbarbhuyia commented on server/routes/flag.js
> +        origin: ['http://localhost:3000'] // Client URL -- http://localhost:3000 for testing
Another one

2023-10-29 00:36 UTC, abrarbarbhuyia approved these changes

2023-10-29 00:36 UTC, abrarbarbhuyia commented on server/routes/flag.js
> -        origin: ['http://localhost:3000'] // Client URL -- http://localhost:3000 for testing
Might need to add FRONTEND_URL="" in .env for server.
Then call it with process.env.FRONTEND_URL here

2023-10-29 00:38 UTC, abrarbarbhuyia approved these changes

2023-10-29 00:38 UTC, abrarbarbhuyia commented on server/routes/flag.js
> -        origin: ['http://localhost:3000'] // Client URL -- http://localhost:3000 for testing
OMG Ignore me, sorry.

Can you change this back to
const corsOptions = {
  origin: ['http://localhost:3000', 'https://sentinel-frontend.vercel.app'],
};

T_T

2023-10-29 00:40 UTC, merged